# Generated by Django 5.2.6 on 2025-09-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameroom_creator_gameroom_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='current_turn_team',
            field=models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1),
        ),
    ]
