# Generated by Django 5.2.6 on 2025-09-14 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_usermessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guess',
            index=models.Index(fields=['room', 'timestamp'], name='game_guess_room_id_28ca01_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['room', 'team'], name='game_player_room_id_284c24_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['room', 'is_winner'], name='game_player_room_id_8959a8_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['room', 'joined_at'], name='game_player_room_id_1050c2_idx'),
        ),
    ]
